networks:
  web-net:
    driver: bridge

services:

  nginx:
    restart: always
    image: nginx:1.20
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/webroot:/var/www/html
      - ./nginx/autodiscover/:/etc/nginx/autodiscover  
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
    networks:
      - web-net

  certbot:
    image: certbot/certbot
    container_name: certbot-auto
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./nginx/webroot:/var/www/html
      - ./autorenew/certbot-renew.sh:/certbot-renew.sh
    entrypoint: ["/bin/sh", "-c", "chmod +x /certbot-renew.sh && /certbot-renew.sh"]
    networks:
      - web-net
